ThingEngineer/PHP-MySQLi-Database-Class

MysqliDb.php
readme.md
tests.php

Bugfixes an features

---

MysqliDb.php

It's valid to increment a field by a float, this allows both ints and floats to be used in increments and decrements, while still keeping the default (int)1.

Changed inc() and dec() methods to support float

---

MysqliDb.php
dbObject.php

It seems more convenient/conventional to throw exceptions so they can be
caught, if desired.  Using trigger_error creates a fatal error.

Swapped trigger_error for exceptions

---

MysqliDb.php

```sql
CREATE TABLE IF NOT EXISTS `users` (
`user_id` int(11) NOT NULL auto_increment,
`username` varchar(50) NOT NULL,
PRIMARY KEY  (`user_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS `users_profiles` (
`id` int(11) NOT NULL auto_increment,
`user_id` int(11) NOT NULL,
`real_name` varchar(20) NOT NULL,
`birthday_time` int(11) NOT NULL,
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;
```
```php
$db->join("users_profiles", "using(user_id)", "LEFT")
->where( 'user_id',  $id)
->get('users');
```
Fatal error: Uncaught exception 'Exception' with message 'Problem preparing query (SELECT * FROM a_users LEFT JOIN a_users_profiles on using(user_id) WHERE user_id = ? ) You have an error in your SQL syntax; check the manual that corresponds to your …

Join: do not add 'on' if using() condition is used

---

dbObject.php

For solve bug with table without a primaryKey

dbObject - Join Method add primaryKey as var

---

MysqliDb.php
tests/dbObjectTests.php

- added missing space ' '  befor appending operator to query in _buildCondition() default statement for NULL comparison
- changed shorthand php `<?` to default `<?php` in dbObjectTests for better downward compability

fixed missing space before operator when comparing against NULL

---

MysqliDb.php
readme.md

Adding support for mysql error codes

---

MysqliDb.php

Adding mysqli error number to throwed exception in _prepareQuery() method.

Adding error number to exception

---

MysqliDb.php
readme.md
tests/mysqliDbTests.php

this is a first implementation for `MysqliDB:: insertMulti()` method to insert multiple datasets at once by utilizing mysql-transactions.
Please excuse the additional changed lines in the commits, where only spaces where deleted. My Editor does this by default.
This is only a proposal and therefor may be not the best or fastest solution.
The changes include:
-  added `MysqliDB::insertMulti()` method into `MysqliDb.php`
- added tests for insertMulti implementation in `tests/mysqliDbTests.php`
- added small documentation to `readme.md`
Please tell, if something should be changed or does not adapt the classes coding style.

insertMulti implementation by using transactions

---

dbObject.md
dbObject.php

In current version, every column of a table mapped into a `dbObject` is accessible through the magic getter method and editable through magic setter method. 
But sometimes it's important to hide some fields/columns from the model (for example, access user password with `$user->password` is not that good, as updating it with `$user->password = "random"`).
I've added a `$hidden` array, that holds column names that can't be accessed with magic methods. This array must be declared into the model class, as the other arrays supported by the library.
```php
class User extends dbObject {
protected $dbFields = array(
'username' => array('text', 'required'),
'password' => array('text', 'required'),
'is_admin' => array('bool'),
'token' => array('text')
);
protected $hidden = array(
'password', …
```

Add "hidden" columns/fields into dbObject

---

MysqliDb.php

Basically, if the 3rd parameter received by the `orderBy` function is a string, this string is going to be considered a REGEXP. You still can send an array to order by field.
Example of use:
$MySqliDb->orderBy('name', 'desc', '^[a-zA-Z0-9]')->orderBy('name', 'desc');
// Is going to order by name but placing those name starting with special charaters at the end

Adding ORDER BY REGEXP possibilites

---

MysqliDb.php

Allow garbage collection to close mysqli instance connection, instead of closing it in the destructor. #622

Remove __destructor from MysqliDb

---

MysqliDb.php

Ability to use multiple connections.
How to use it
1. create a mysqlidb instance with params for the 1st database
```
$db = new MysqliDB($host, $username, $password);
```
2. add params for the 2nd database (via `addConnection` method)
```
$db->addConnection('second', ['host'=>$host2, 'username'=>$username2, 'password'=>$password2]);
```
3. switch to the 2nd connection for the next query via `connection`
```
$db->connection('second')->get('seconddb_table');
```
... or the 1st connection will be used
```
$db->get('firstdb_table');
```
ps.: selected connection (step 3) will be unselect after request done (at `reset` method).

Multiple connections

---

readme.md

- Fixed damaged headlines where spaces were missing

Fixed readme headlines

---

dbObject.php

dbObject has a switch case in line 644 : written as ";" .

FIX #661: Incorrect switch case

---

MysqliDb.php

with this change we are able to call this MySQLi Database Class the same way as before.

use default connection when not specified

---

MysqliDb.php

Sometimes you have to use GROUP BY in SQL with Spaces in it.
The old implementation deleted all spaces in $groupByField
Eg "IF(qv.idValue IS NULL, UUID(), qv.idValue)" would become "IF(qv.idValueISNULL,UUID(),qv.idValue)"
In case of grouping all equal but not null values, you need a function call like in above example.
Example of stacktrace:
`Uncaught Exception: Unknown column 'qv.idValueISNULL' in 'group statement' query`

Fixed groupBy with spaces in field declaration

---

dbObject.php

One can skip fields during validating or saving the object. Just like
`$user->skip('password')->save()`
or
`$user->skip(['password','email'])->save()`
sometimes one needs to undo added skips. One needs
`$user->skip(false)->save()`
and there no more skips!

one can skip some fields during validation & save

---

dbObject.php

```php
$currentPage = 1;
dbObject::$pageLimit = 50;
$objects = dbObject::paginate($currentPage);
$totalPages = dbObject::$totalPages;
$totalObjects = dbObject::$totalCount; // we can get total objects now
```

Bring up the $totalCount in dbObject::paginate()

---

MysqliDb.php

implode(): Passing glue string after array is deprecated.
Fixes: #868

Fix implode() PHP 7.4

---

MysqliDb.php

Removed space before the parenthesis  of function getLastErrno to solve the issue #976

#976 - fixed the issue number #976 by removing the space between function name and the parenthesis.

---

MysqliDb.php

Get() currently accepts values ​​of array type

fix the field type of phpdoc comment

---

MysqliDb.php

Hi, in the MysqliDb.php file and function "_buildInsertQuery" there is a wrong use of the implode function.

Fixed bug in new-v2.9.3 for wrong implode function use

---

MysqliDb.php

This PR addresses a potential issue in the `rawAddPrefix` method where, if the provided SQL query does not contain keywords like "from", "into", "update", "join", or "describe" (e.g. functions and procedures), the `$table` array would be empty, leading to a PHP deprecated warning in the newer versions. 
The proposed solution adds a conditional check to ensure that there are table name matches before proceeding with the replacement.

Fix potential null issue in rawAddPrefix method
