MysqliDb.php, readme.md, tests.php
Addressed most of the valid issues
=> Bugfixes an features

MysqliDb.php, readme.md
Added **has** helper method + added doc for it in readme.md. Fixed closing php tag.
=> Some features added!

dbObject.md
Improved the grammar and cleanliness of the example code.
=> Made a few changes to the documentation

MysqliDb.php
- Some small refactoring to comply PSR 1 & 2 standard
- Exceptions instead of dying
- new self() in subQuery method
=> PSR 1&2 code refactoring and exceptions instead of die()

MysqliDb.php
- Huge PHP DocBlock update. Added missed params, method descriptions, etc.
- Small code improvements to comply PSR-1, PSR-2 PHP Coding standards (I suggest to use that common standads in MysqliDb).
- Array => array, etc.
- unified method naming (but no changes to methods that start with underscore)
All tests are passing and changes do not break any functionality.
=> PHP DocBlock update. Some small PSR-2 code refactoring.

MysqliDb.php
Changed *having* function to perform identically to *where* function
=> Fixed Having

dbObject.php
example
$file = file::with('realFile')->ById($fileId);
$file->realFile === null ; // This is false, after this fix is true
=> fix $obj->relatedObj === null when not exists

dbObject.php
- Fixed using [byId](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/568) error in active record pattern 
- Provide [pagination with data type](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/561) (object, array, json)
=> Fixed byId and provide pagination with data type

MysqliDb.php
Delete statement should only return false if an error occurred, not if sql operation completed successfully but yielded no changes
=> fixed delete statement return value

MysqliDb.php
=> Fix issue where orderBy strips spaces from fieldname

MysqliDb.php
while preparing/unprepared query if the connection was lost (errno 2006 https://dev.mysql.com/doc/refman/5.7/en/gone-away.html)
+ some phpdoc improvement
=> Automatically reconnect to the MySQL server

dbObject.md
So the Markdown compiler understands the titles.
=> Add spaces after '#'

readme.md
Some small grammar/spelling changes.
=> Small changes to readme.md

dbObject.php
A fix for the objects mapping.
=> Keep objects mapped

MysqliDb.php
Would like to know count of records deleted - tested and works.  Left the return same for compatibility but updated comment.
=> Set db->count with affected_rows on delete

MysqliDb.php
PHPDoc updated for some param/return/throws parts
=> Better PHPDoc

dbObject.md, dbObject.php
Add getValue method for models objects.
=> Add getValue method for models objects.

MysqliDb.php
Prefix add table name All SQL query.
=> Prefix add table name All SQL rawQuery

dbObject.php
Objects are not json encoded on save because there is only a check if it's not an array
=> Added check if jsonField is not an object so it also gets json decoded

dbObject.php
So we can use the prefix in with() relations.
=> added prefix to dbobject to be included in with() relation
